### ISSUE TITLE
I get some errors.there are no  wsol.R matching.R and UtilitaryFunc.R in your packages.

### ISSUE THREAD

**Issue by zdlspace0528** [jeremylhour/pensynth#4]
Dear Professor,
I have downloaded the R package —regsynth— from your github.When I run the codes of your example “EXE_VoterTurnout.R”,I get some errors.there are no 
wsol.R matching.R and UtilitaryFunc.R in your packages.Can you help me to solve the problem?

Best
Raymond

> ### Load packages
> library("MASS")
> library("ggplot2")
> library("gtable")
> library("grid")
> library("reshape2")
> library("LowRankQP")
LowRankQP 1.0 loaded
Copyright J.T. Ormerod & M. P. Wand 2020
> library("gsynth")
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
> library("foreach")
> library("doParallel")
> library("geometry")
> 
> ### Load user functions
> source("functions/wsol.R")
Error in file(filename, "r", encoding = encoding) : 无法打开链结
此外: Warning message:
In file(filename, "r", encoding = encoding) :
  无法打开文件'functions/wsol.R': No such file or directory
> source("functions/wsoll1.R")
> source("functions/matchDGP.R")
> source("functions/wATT.R")
> source("functions/matching.R")
Error in file(filename, "r", encoding = encoding) : 无法打开链结
此外: Warning message:
In file(filename, "r", encoding = encoding) :
  无法打开文件'functions/matching.R': No such file or directory
> source("functions/matchest.R")
> source("functions/regsynth.R")
> source("functions/regsynthpath.R")
> source("functions/TZero.R")
> source("functions/synthObj.R")
> source("functions/perm.test.R")
> source("functions/conf.interval.R")
> source("functions/bias.R")
> source("functions/UtilitaryFunc.R")
Error in file(filename, "r", encoding = encoding) : 无法打开链结
此外: Warning message:
In file(filename, "r", encoding = encoding) :
  无法打开文件'functions/UtilitaryFunc.R': No such file or directory

**Comment by jeremylhour** [comment]
Hi there, 

these files are not used in this script. You can not load them and it should still work. I erased these lines and committed changes. You should pull the repo again.

By the way, there are no guarantees for the these scripts beside the example on Lalonde data used in the paper. For the others, there might remain bugs, coding mistakes, etc.
